apiVersion: v1
kind: Service
metadata:
  labels:
    app: notypie-ui
  name: notypie-ui
  namespace: notypie-dev
spec:
  selector:
    app: notypie-ui
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
